### ISSUE TITLE
[BUG] Configuration menu not appearing for players

### ISSUE THREAD

**Issue by Silveressa** [ShoyuVanilla/FoundryVTT-Chat-Portrait#89] opened 2022-01-14 07:17 UTC
**Module Version:** v0.5.33

Describe the bug
The menu to configure the module is not available for players.

To Reproduce
1. Log in as a player
2. Go to "configure settings/Module Settings"
3. The Chat Portrait  configuration menu does not appear.

****Expected behavior****
The configuration menu the GM sees should appear for the players so they can configure the appearance of the portrait window as desired.

****Foundry Version:**** 
Version 9 build 272

**Comment by p4535992** [comment] 2022-01-14 11:56
Is not a bug, is a wanted thing, to much bad feedback in the past.
What properties would you like players to see?

**Comment by Silveressa** [comment] 2022-01-14 19:35
I was hoping for players to have the ability to resize the portraits to their liking, since currently I see this perfectly sized image for the players portrait:
![Char swap](https://user-images.githubusercontent.com/45724117/149574449-50157248-ecfa-44a6-9324-42e38212191a.jpg)

But to my player the portrait looks like this with the upper half of the image cut off:

![Char swap](https://user-images.githubusercontent.com/45724117/149574720-6b30668b-0c02-4c89-a1a5-1428d4f5ce25.jpg)

**Comment by p4535992** [comment] 2022-01-14 20:57
Now that is strange . The css should be manage that.
What browser are the player using ?
is it an online world that I can access temporarily?

**Comment by Silveressa** [comment] 2022-01-14 21:14
They're using Vivaldi, which apparently is what's causing the issue, after having them test it in other browsers they found  it renders just fine in Firefox and Chrome. (And they're fine with using Firefox to connect to game sessions)

So not a huge issue any longer tbh.

Though regarding the original request, letting each of my players be able to scale the portrait size to their liking would be ideal, given one of my other players has vision issues and prefers scaling fonts and thumbnails larger than usual so they can make them out easily, so a way for them to do that would be ideal, but if it's not feasible I completely understand.

**Comment by Joonasm** [comment] 2022-01-19 17:36
Adding onto this, my players are having problems where after i disable OOC portraits they still see them

**Comment by p4535992** [comment] 2022-04-30 10:23
Form version 0.7.0 , many settings are now scoped to 'client' instead of 'world', i'll close this issue.

**Closed by p4535992** 2022-04-30 10:23 UTC
Labels: enhancement
